providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]
cacheDirectories = ["/root/.local/share/pnpm/store"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"