import type { Metadata } from "next";
import "./globals.css";
import { ThemeProviders } from './theme-providers'
import siteMetadata from '@/data/siteMetadata'
import ThemeSwitch from '@/components/theme-switch';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={siteMetadata.locale} suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProviders>
          <header className="flex justify-end">
            <ThemeSwitch />
          </header>
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
