import type { Metadata } from "next";
import "./globals.css";
import { ThemeProviders } from './theme-providers'
import siteMetadata from '@/data/siteMetadata'
import ThemeSwitch from '@/components/theme-switch';
import LangSwitch from '@/components/LangSwitch';
import { dir } from 'i18next'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return siteMetadata.languages.map((lng) => ({ lng }))
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>
}>) {
  const { lng } = await params
  return (
    <html lang={lng} dir={dir(lng)} suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProviders>
          <header className="flex justify-end">
            <ThemeSwitch />
            <LangSwitch />
          </header>
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
